services:
  service-jbot-discord-bot:
    build:
      context: .
      dockerfile: Dockerfile.api_server_discord_jbot
    container_name: jbot-discord-bot
    environment:
      - PYTHONUNBUFFERED=1
      - SECRET_KEY=${SECRET_KEY}
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
      - DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}
      - DISCORD_CLIENT_SECRET=${DISCORD_CLIENT_SECRET}
      - DISCORD_REDIRECT_URI=${DISCORD_REDIRECT_URI}
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
      - YOUTUBE_USERNAME=${YOUTUBE_USERNAME}
      - YOUTUBE_PASSWORD=${YOUTUBE_PASSWORD}
    networks:
      - jbot-network
    volumes:
      - ./api_server_discord_jbot:/app/api_server_discord_jbot
      - ./auth:/app/auth
networks:
  jbot-network:
    driver: bridge